simplesocial/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from django.urls import path
app_name = 'accounts'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
    

    path(r"profile/(?P<slug>[-\w]+)/", views.profile.as_view(), name = "profile"),
    #path(r"update/<int:pk>", views.Editprofile.as_view(), ),
    
    path(r"update/(?P<slug>[-\w]+)/", views.Editprofile.as_view(), name = "update"),

]

simplesocial/posts/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),

    #url(r"viewall/$", views.PostList.as_view(), name="viewall"),
    #path('by/<slug:username>', views.UserPosts.as_view(),name="for_user"),

    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),

    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
   # url(r"update/(?P<post_id>\d+)/$",views.UpdateView,name="update"),
    path('update/<post_id>',views.UpdatePost,name='update')
]

simplesocial/simplesocial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.urls import path

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    path('oauth2/', include('django_auth_adfs.urls')),
    url(r"^test/$", views.sample_view, name="test"),
    url(r"^CreateProfile/$", views.CreateProfile.as_view(), name="CreateProfile"),
    url(r"^test2/$", views.TestPage.as_view(), name="test2"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^groups/",include("groups.urls", namespace="groups")),
]
urlpatterns+=static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

simplesocial/accounts/models.py
from django.contrib import auth
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.utils.text import slugify
from groups.models import  Group


POSITION_CHOICES=(
    ('prof','Faculty'),
    ('stud', 'Student'),
    ('alumnus','Alumnus'),
)
GENDER_CHOICES=(
    ('anon','Prefer Not To Say'),
    ('m', 'Male'),
    ('f','Female'),
)
BRANCH_CHOICES=( 
('bt','Biotech'), 
('ch', 'Chemical'), 
('cse','Computer Science'), 
('mnc','Mathematics'), 
('ep','Engineering Physics'),
('ece','Electronics'),
('ee','Electrical'),
('me','Mechanical'),
('cv','Civil'),
('cst','CST') 
)

class UserProfile(models.Model):
    name = models.CharField(default=None,max_length=256,null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, default=None)
    slug = models.SlugField(allow_unicode=True, unique=True,  default=None)
    position= models.CharField(max_length=255, choices=POSITION_CHOICES, default='stud')
    photo= models.ImageField(default= None,null=True)
    username = models.CharField(max_length=256)
    aboutme = models.TextField(default=None,null=True)
    branch = models.CharField(max_length=255, choices=BRANCH_CHOICES, default='bt')
    cpi = models.FloatField(default=None,null=True)
    gender = models.CharField(max_length=255, choices=GENDER_CHOICES, default='anon')
    linkedin = models.CharField(default=None,max_length=256,null=True)
    # resume = models.FileField(default=None,null=True)
    
    def save(self, *args, **kwargs):
        kc = self.username
        print(kc)
        self.slug = slugify(kc)
        super().save(*args, **kwargs)


class User(auth.models.User, auth.models.PermissionsMixin):

   def str(self):
        return "@{}".format(self.username)

simplesocial/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ("username", "email", "password1", "password2")
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].label = "Display name"
        self.fields["email"].label = "Email address"

simplesocial/accounts/views.py
from django.views.generic.edit import UpdateView
from accounts.models import UserProfile
from accounts import models
from django.contrib.auth import login, logout
from django.urls import reverse_lazy
from django.views.generic import (
  CreateView,
  DetailView,
  UpdateView


)
from django.views.generic.detail import DetailView
from django.shortcuts import render

from . import forms

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "accounts/signup.html"

class profile(DetailView):
    models= models.UserProfile

    template_name= 'accounts/profile_detail.html' 
    queryset= UserProfile.objects.all()
    context = {
        "first_name": "Anjaneyulu",
        "last_name": "Batta",
        "address": "Hyderabad, India"
    }
    

class Editprofile(UpdateView):
    
    models= models.UserProfile
    template_name= 'accounts/editprofile.html' 
    print("debug")
    success_url='/groups/'
    queryset= UserProfile.objects.all()
    fields = ( "name",  "username", "position", "gender", "branch", "cpi", "photo", "aboutme", "linkedin")
    model = UserProfile
    select_related = ("post")
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()

        owner = self.request.user
        owner.save()
        return super().form_valid(form)

simplesocial/accounts/templates/accounts/editprofile.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block content %}
<div class="container"  style="padding-top: 15%;">
    <div style="padding-bottom:5%">

        <h1>Edit profile</h1>
    <form method="POST"  enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Edit" class="btn btn-primary">
    </form>
    </div>
</div>
{% endblock %}

simplesocial/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Login" class="btn btn-default">
    </form>
</div>
{% endblock %}

simplesocial/accounts/templates/accounts/profile_detail.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div style="padding-top: 7%;">
    <div class="section section-padding">
        <div class="container">
            <div class="row mb-n5">

                <div class="col-lg-8 col-12 mb-5 pr-lg-5">

                    <!-- Company Details Start -->
                    <div class="company-details">
                    <h3 class="mb-3">{{ object.name }}</h3>
                    <h4 class="mb-3">Username : {{object.user.userprofile.username}}</h4>
                    {% if object.position == "stud" %}
                        <h5 class="mb-3">Position :  Student </h5>
                    {% elif object.position == "prof" %}
                        <h5 class="mb-3">Position :  Faculty </h5>
                    {% elif object.position == "alumnus" %}
                        <h5 class="mb-3">Position :  Alumni </h5>
                    {% endif %}                    
                    </div>
                    <!-- Company Details Start -->
                    <div class="company-details">
                        {{ object.aboutme }}         
                    </div>
                </div>

                <!-- Company Sidebar Wrap Start -->
                <div class="col-lg-4 col-12 mb-5">
                    <div class="sidebar-wrap">
                        <!-- Sidebar (Company) Start -->
                        <div class="sidebar-widget">
                            <div class="inner">
                                <div class="sidebar-company">
                                    <span class="company-logo"><img src="{{ object.photo.url }}" alt="company-1"></span>
                                    <h6 class="title"> {{object.name}} </h6>
                                    <ul>
                                        <li><strong>Branch:</strong> {{ object.branch }}</li>
                                        <li><strong>Gender:</strong> {{ object.gender }}</li>
                                        <li><strong>CPI:</strong> {{ object.cpi }}</li>
                                        <li><strong>Skills:</strong> <a
                                                href="https://demo.hasthemes.com/keller-preview/keller/company-single.html#">Website</a>,
                                            <a
                                                href="https://demo.hasthemes.com/keller-preview/keller/company-single.html#">Software</a>
                                        </li>
                                        <li><strong>Founded:</strong> 2006</li>
                                        <li><strong>Linkedin:</strong> <a href="{{object.linkedin}}">{{object.linkedin}}</a>
                                        </li>
                                    </ul>
                                </div>

                            
                            </div>
                            
                        <div class="inner">
							<div class="col-xl-auto col-lg-12 col-sm-auto col-12 p-2">
								<a href="{% url 'accounts:update' slug=user.userprofile.username %}"><button type="button" class="btn btn-info">Edit Profile</button></a>
                           </div>

						</div>
                        </div>
                        <!-- Sidebar (Company) End -->

                    </div>
                </div>
                <!-- Company Sidebar Wrap End -->

            </div>
        </div>
    </div>
    <!-- Company List End -->

    <!-- Footer Top Section Start -->
    <!-- Footer Top Section End -->

    <!-- JS
============================================ -->

    <!-- Google Map API JS -->
    <script src="./companypage_files/js"></script>

    <!-- Vendors JS -->
    <script src="./companypage_files/modernizr-3.6.0.min.js.download"></script>
    <script src="./companypage_files/jquery-3.4.1.min.js.download"></script>
    <script src="./companypage_files/bootstrap.bundle.min.js.download"></script>

    <!-- Plugins JS -->
    <script src="./companypage_files/slick.min.js.download"></script>
    <script src="./companypage_files/jquery.waypoints.min.js.download"></script>
    <script src="./companypage_files/jquery.counterup.min.js.download"></script>
    <script src="./companypage_files/jquery.parallax.js.download"></script>
    <script src="./companypage_files/jquery.ajaxchimp.min.js.download"></script>
    <script src="./companypage_files/ion.rangeSlider.min.js.download"></script>
    <script src="./companypage_files/jquery.scrollUp.min.js.download"></script>

    <!-- Main Activation JS -->
    <script src="./companypage_files/main.js.download"></script><a id="scrollUp"
        href="https://demo.hasthemes.com/keller-preview/keller/company-single.html#top"
        style="position: fixed; z-index: 2147483647; display: none;"><i class="fas fa-arrow-up"></i></a>


</div>
{% endblock %}

simplesocial/accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block content %}
<div class="container">
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Sign Up" class="btn btn-default">
    </form>
</div>
{% endblock %}