simplesocial/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from django.urls import path
app_name = 'accounts'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
    

    path(r"profile/(?P<slug>[-\w]+)/", views.profile.as_view(), name = "profile"),
    #path(r"update/<int:pk>", views.Editprofile.as_view(), ),
    
    path(r"update/(?P<slug>[-\w]+)/", views.Editprofile.as_view(), name = "update"),

]

simplesocial/posts/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),

    #url(r"viewall/$", views.PostList.as_view(), name="viewall"),
    #path('by/<slug:username>', views.UserPosts.as_view(),name="for_user"),

    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),

    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
   # url(r"update/(?P<post_id>\d+)/$",views.UpdateView,name="update"),
    path('update/<post_id>',views.UpdatePost,name='update')
]

simplesocial/simplesocial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.urls import path

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    path('oauth2/', include('django_auth_adfs.urls')),
    url(r"^test/$", views.sample_view, name="test"),
    url(r"^CreateProfile/$", views.CreateProfile.as_view(), name="CreateProfile"),
    url(r"^test2/$", views.TestPage.as_view(), name="test2"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^groups/",include("groups.urls", namespace="groups")),
]
urlpatterns+=static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

simplesocial/posts/models.py
from django.conf import settings
from django.urls import reverse
from django.db import models

import misaka
from phonenumber_field.modelfields import PhoneNumberField

from groups.models import  Group

from django.contrib.auth import get_user_model
User = get_user_model()
YEAR_CHOICES=(
    ('1','1st year'),
    ('2', '2nd year'),
    ('3','3rd year'),
    ('4','4th year'),
    ('na','Not Applicable'),
)

RESULT_CHOICES=(
    ('nd','Not Decided'),
    ('r', 'Rejected'),
    ('a','Accepted'),
)
 
BRANCH_CHOICES=( 
('bt','Biotech'), 
('ch', 'Chemical'), 
('cse','Computer Science'), 
('mnc','Mathematics'), 
('ep','Engineering Physics'),
('ece','Electronics'),
('ee','Electrical'),
('me','Mechanical'),
('cv','Civil'),
('cst','CST'), 
('na','Not Applicable') 
)

class Post(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE, related_name="posts")
    created_at = models.DateTimeField(auto_now=True)
    group = models.ForeignKey(Group,on_delete=models.CASCADE, related_name="posts",null=True, blank=True)
    name = models.CharField(max_length=255, default=None, null=True)    
    year = models.CharField(max_length=255, choices=YEAR_CHOICES, default='na', null=True)
    qualifications= models.TextField(blank=True, default='', null=True)
    qual_html= models.TextField(blank=True, default='', null=True, editable=False)
    contact_number = PhoneNumberField( default=None, null=True)
    email_ID = models.EmailField( default=None, null=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    answer_to_questions_if_any = models.TextField(blank=True, default='', null=True)
    answer_to_questions_if_any_html= models.TextField(blank=True, default='', null=True, editable=False)
    branch = models.CharField(max_length=255, choices=BRANCH_CHOICES, default='na')
    # resume = models.FileField(default= None,null=True)
    resume=models.FileField(default= None, null=True,blank=True,upload_to="resumes/")
    # accepted=models.CharField(max_length=255, default='Not Decided')
    accepted = models.CharField(max_length=255, choices=RESULT_CHOICES, default='nd')

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        self.qual_html = misaka.html(self.qualifications)
        self.answer_to_questions_if_any_html = misaka.html(self.answer_to_questions_if_any)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse(
            "posts:single",
            kwargs={
                "username": self.user.username,
                "pk": self.pk
            }
        )

    class Meta:
        ordering = ["-created_at"]
        unique_together = ["user", "message"]

simplesocial/posts/forms.py
from django import forms

from posts import models

from django.forms import ModelForm
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        fields = ("message", "group", "resume")
        model = models.Post

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super().__init__(*args, **kwargs)
        if user is not None:
            self.fields["group"].queryset = (
                models.Group.objects.filter(
                    pk__in=user.groups.values_list("group__pk")
                )
            ) 

class UpdateForm(ModelForm):
    class Meta:
        model = Post
        fields = ['accepted']

simplesocial/posts/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import Http404
from django.views import generic
from django.views.generic import UpdateView
from braces.views import SelectRelatedMixin
from .forms import UpdateForm
from django.shortcuts import redirect, render
from . import forms
from . import models
from django.http import HttpResponseRedirect

from accounts.models import UserProfile 
from .models import Post 

from django.contrib.auth import get_user_model
User = get_user_model()


class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ("user", "group")
    template_name = "posts/user_post_list.html"


class UserPosts(generic.ListView):
    model = models.Post
    template_name = "posts/user_post_list.html"

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"] = self.post_user
        return context


class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ("user", "group")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(
            user__username__iexact=self.kwargs.get("username")
        )


class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    # form_class = forms.PostForm
    # fields = ('message','group')
    fields = ("group","name", "branch", "year","message","qualifications","contact_number","email_ID","answer_to_questions_if_any","resume")
    model = models.Post

    # def get_form_kwargs(self):
    #     kwargs = super().get_form_kwargs()
    #     kwargs.update({"user": self.request.user})
    #     return kwargs
    success_url='/groups/'
    def form_valid(self, form):
        # self.object.name = self.request.user.userprofile.name
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ("user", "group")
    success_url = reverse_lazy("groups:all")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, "Post Deleted")
        return super().delete(*args, **kwargs)

def UpdatePost(request,post_id):
    post=Post.objects.get(pk=post_id)
    form=UpdateForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('groups:yourall')
    return render(request,'posts/update_post.html',{'post':post,'form':form})

simplesocial/posts/templates/posts/_post.html
<div class="post media" style="padding-bottom:5%;">
  
	<div class="media-body">
		<h6>
			<strong>Username : </strong><a href="{% url 'accounts:profile' slug=user.userprofile.username %}">@{{ post.user.userprofile.username }}</a>
			<br/>
			<strong>Applied on : </strong><time class="time">{{ post.created_at }}</time>

			
			{% if post.accepted == "a" %}
			<br>
			<button type="button" class="btn btn-success btn-sm">Selected</button>
			{% endif %}
		</h6>
		<h4 class="media-heading">
			
			<!-- {% if post.group %}
			<span class="group-name"><a href="#">{{ post.group.name }}</a></span>
			{% endif %} -->
		</h4>
		<div style="padding-top:3%">
			<h6>
				<div><span style="font-weight: 600;">Name : </span><span style="font-weight: 400;">{{ post.name }}</span></div>
				<div><span style="font-weight: 600;">Current Year : </span><span style="font-weight: 400;">{{ post.year }}</span></div>
				<div><span style="font-weight: 600;">Contact Number : </span><span style="font-weight: 400;">{{ post.contact_number }}</span></div>
				<div><span style="font-weight: 600;">Email ID : </span><span style="font-weight: 400;">{{ post.email_ID }}</span></div>
				<div><span style="font-weight: 600;">Resume Uploaded : </span><a href = "" style="text-decoration: underline;"><span style="font-weight: 400;">Click Here</span></a></div> 

			</h6>
			<div style="padding-top:2%">
				<h6 style="display: inline; font-weight: 600;">Your Message : </h6>
				<p style="display: inline;">{{ post.message_html | safe }}</p>
			</div>
			<div style="padding-top:2%">
				<h6 style="display: inline; font-weight: 600;">Your Qualifications : </h6>
				<p style="display: inline;">{{ post.qual_html | safe}}</p>
			</div>
			<div style="padding-top:2%">
				<h6 style="display: inline; font-weight: 600;">Your Answer to Additional Questions (if any) : </h6>
				<p style="display: inline;">{{ post.answer_to_questions_if_any_html | safe}}</p>
			</div>
			<div style="padding-top:2%">
				<h6 style="display: inline; font-weight: 600;">Result : </h6>
				<p style="display: inline;">{{ post.accepted}}</p>
			</div>
		</div>

		<div class="media-footer" style="padding-top:2%">
			{% if user.is_authenticated and post.user == user and not hide_delete %}
				<button type="button" class="btn btn-md btn-danger">
					<a href="{% url 'posts:delete' pk=post.pk %}" title="delete">
						Delete
					</a>
				</button>
			{% endif %}
		</div>

		<div class="media-footer" style="padding-top:2%">
			{% if user.is_authenticated and post.group.creator == user %}
				<button type="button" class="btn btn-md btn-danger">
					<a href="{% url 'posts:update' post.id %}" title="update">
						Change Result Status
					</a>
				</button>
			{% endif %}
		</div>
		
	 
		
	</div>
</div>

simplesocial/posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block content %}
<div class="posts-page">
	<div class="container">
		{% block prepost%}{% endblock %}
		{% block post_content %}{% endblock %}
		{% block post_post%}{% endblock %}

	</div>
</div>
{% endblock %}

simplesocial/posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}


{% block post_content %}
<h3>Are you sure you want to delete this application?</h3>

<div class="posts">
	{% include "posts/_post.html" with post=object hide_delete=True %}
</div>

<form method="POST">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
	<a href="{% url 'groups:single' slug=object.group.slug %}" class="btn btn-simple btn-large btn-default">Cancel</a>
</form>

{% endblock %}

simplesocial/posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<div style="padding-top: 15%;"class="col-md-8">
    {% include "posts/_post.html" %}
</div>
{% endblock %}

simplesocial/posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}

{% load bootstrap3 %}

{% block post_content %}
<div style="padding-top:10%; padding-bottom: 5%;">
<h4>Apply for this intern</h4>
<form method="POST" action="{% url 'posts:create' %}" id="postForm" enctype="multipart/form-data">
	{% csrf_token %}
	{% bootstrap_form form %}
	<input type="submit" value="Post" class="btn btn-primary btn-large">
</form>
</div>
{% endblock %}

simplesocial/posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}
{% load humanize %}

{% block pre_post_content %}
<div class="col-md-4">
	{% if request.user.is_authenticated %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">Your Groups</h5>
			<ul class="list-unstyled">
				{# {% get_user_groups as user_groups %}#}
				{% for member_group in get_user_groups %}
				<li class="group li-with-bullet">
					<a href="{% url 'groups:single' slug=member_group.group.slug %}">{{ member_group.group.name
						}}</a>
				</li>
				{% endfor %}

			</ul>
		</div>
	</div>
	{% endif %}
	<div class="card card-with-shadow">
		<div class="content">
			<h5 class="title">All groups</h5>
			<ul class="list-unstyled">
				{# {% get_other_groups as other_groups %}#}
				{% for other_group in get_other_groups %}
				<li class="group li-with-bullet"><a href="{% url 'groups:single' slug=other_group.slug %}">{{
						other_group.name }}</a></li>
				{% endfor %}
			</ul>




		</div>
	</div>
</div>
{% endblock %}
{% block post_content %}
<div class="col-md-8">
	{% for post in post_list %}
	{% include "posts/_post.html" %}
	{% endfor %}
</div>
{% endblock %}

simplesocial/posts/templates/posts/update_post.html
{% extends "posts/post_base.html" %}

{% load bootstrap3 %}

{% block post_content %}

<div style="padding-top:10%; padding-bottom: 5%;">
    <h1>Update Status</h1>
    <br/>
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Update" class="btn btn-secondary">
    </form>
</div>

{% endblock %}

simplesocial/posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}
{% endblock %}

{% block post_content %}
<div style="padding-top: 15%;">
	<div class=" col-md-4">
		<h1>@{{ user.userprofile.username }}</h1>
		<h2>All applications</h2>
	</div>
	<div class="col-md-8">
		{% for post in post_list %}
		{% if post.user == user %}
		<h3>In {{post.group}}</h3>
		{% include "posts/_post.html" %}
		{% endif %}
		{% endfor %}
	</div>
</div>
{% endblock %}