simplesocial/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views
from django.urls import path
app_name = 'accounts'

urlpatterns = [
    url(r"login/$", auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
    url(r"logout/$", auth_views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
    

    path(r"profile/(?P<slug>[-\w]+)/", views.profile.as_view(), name = "profile"),
    #path(r"update/<int:pk>", views.Editprofile.as_view(), ),
    
    path(r"update/(?P<slug>[-\w]+)/", views.Editprofile.as_view(), name = "update"),

]

simplesocial/groups/urls.py
from django.conf.urls import url

from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    url(r"^$", views.ListGroups.as_view(), name="all"),
    url(r"^your/$", views.ListGroups2.as_view(), name="yourall"),
    url(r"^btp/$", views.ListGroupsBTP.as_view(), name="btp"),
    url(r"^new/$", views.CreateGroup.as_view(), name="create"),
    url(r"^posts/in/(?P<slug>[-\w]+)/$",views.SingleGroup.as_view(),name="single"),
    path('searchbar', views.searchbar, name='searchbar'),
    #url(r"join/(?P<slug>[-\w]+)/$",views.JoinGroup.as_view(),name="join"),
    #url(r"leave/(?P<slug>[-\w]+)/$",views.LeaveGroup.as_view(),name="leave"),
]

simplesocial/posts/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),

    #url(r"viewall/$", views.PostList.as_view(), name="viewall"),
    #path('by/<slug:username>', views.UserPosts.as_view(),name="for_user"),

    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),

    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
   # url(r"update/(?P<post_id>\d+)/$",views.UpdateView,name="update"),
    path('update/<post_id>',views.UpdatePost,name='update')
]

simplesocial/simplesocial/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.urls import path

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r"^$", views.HomePage.as_view(), name="home"),
    path('oauth2/', include('django_auth_adfs.urls')),
    url(r"^test/$", views.sample_view, name="test"),
    url(r"^CreateProfile/$", views.CreateProfile.as_view(), name="CreateProfile"),
    url(r"^test2/$", views.TestPage.as_view(), name="test2"),
    url(r"^thanks/$", views.ThanksPage.as_view(), name="thanks"),
    url(r"^admin/", admin.site.urls),
    url(r"^accounts/", include("accounts.urls", namespace="accounts")),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^groups/",include("groups.urls", namespace="groups")),
]
urlpatterns+=static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

simplesocial/groups/models.py
from django.conf import settings
from django.urls import reverse
from django.db import models
from django.utils.text import slugify


import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register = template.Library()

FIELD_CHOICES=(
    ('ml','ML'),
    ('appd', 'APPD'),
    ('webdf','WEBDF'),
    ('webdb','WEBDB'),
    ('sde','SDE'),
)

STATUS_CHOICES=(
    ('ft','Full-Time'),
    ('pt','Part-Time')
)

BRANCH_CHOICES=( 
('bt','Biotech'), 
('ch', 'Chemical'), 
('cse','Computer Science'), 
('mnc','Mathematics'), 
('ep','Engineering Physics'),
('ece','Electronics'),
('ee','Electrical'),
('me','Mechanical'),
('cv','Civil'),
('cst','CST'), 
('na','Not Applicable') 
)


class Group(models.Model):
    creator = models.ForeignKey(User,on_delete=models.CASCADE, related_name="group_creator")
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    #cpi_cutoff = models.DecimalField(max_digits=3, decimal_places=2)
    field_of_job= models.CharField(max_length=255, choices=FIELD_CHOICES, default='sde')
    duration = models.CharField(max_length=255, blank=True, default='', null=True)
    stipend = models.CharField(max_length=255, blank=True, default='', null=True)
    expected_qualifications = models.TextField(blank=True, default='', null=True)
    apply_by = models.CharField(max_length=255,blank=True, default='', null=True)
    start_date= models.CharField(max_length=255,blank=True, default='', null=True)
    additional_questions_to_applicant = models.TextField(blank=True, default='', null=True)
    location = models.CharField(max_length=255, blank=True, default='', null=True)
    vacancy = models.PositiveIntegerField(blank=True, default=1, null=True)
    workstatus = models.CharField(max_length=255, choices=STATUS_CHOICES, default='pt')
    btp=models.BooleanField(default=False, null=True, blank=True)
    branch = models.CharField(max_length=255, choices=BRANCH_CHOICES, default='na')
    finished=models.BooleanField(default=False, null=True, blank=True)
    
    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("groups:single", kwargs={"slug": self.slug})


    class Meta:
        ordering = ["name"]

simplesocial/groups/views.py
from django.contrib import messages
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    PermissionRequiredMixin
)


from django.urls import reverse, path
from django.db import IntegrityError
from django.shortcuts import get_object_or_404, render
from django.views import generic
from groups.models import Group
from . import models

def searchbar(request):
    if(request.method=="POST"):
        searched=request.POST.get("searchbar")
        field = request.POST.get("fieldofjob")
        # print(type(field))
        if field == 'all':
            groupss=Group.objects.filter(name__contains=searched)
        else :
            groupss=Group.objects.filter(name__contains=searched, field_of_job__contains =field)
        return render(request,'groups/searchbar.html',{'searched':searched, 'groupss':groupss})

class CreateGroup(LoginRequiredMixin, generic.CreateView):
    # fields = ("name", "description", "field_of_job")
    fields = ("name", "btp", "branch", "duration", "stipend", "location", "vacancy" ,"workstatus","description", "field_of_job", "expected_qualifications","apply_by", "start_date","additional_questions_to_applicant")

    model = Group
    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.creator = self.request.user
        self.object.save()
        return super().form_valid(form)

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group
 
class ListGroups2(generic.ListView):
    model = Group
    template_name="groups/yourlist.html"

class ListGroupsBTP(generic.ListView):
    model = Group
    template_name="groups/btp_list.html"

simplesocial/groups/templates/groups/btp_list.html
{% extends "groups/group_base.html" %}
{% load static %}
{% block pregroup %}
<div class="row">

	<!-- Job Sidebar Wrap End -->

	<div class="col-md-4" style="padding-top: 15%; padding-bottom: 5%;">
		<div class="content">
			{% if user.is_authenticated %}
			<h5 class="title">
				Logged in as <a href="{% url 'accounts:profile' slug=user.userprofile.username %}">@{{user.userprofile.username}}</a>
			</h5>

			{% endif %}
			<div style="padding-top: 5%; padding-bottom: 15%;">
				<h3 class="title">Search Keywords</h3>
				<form action="{% url 'groups:searchbar' %}" method="POST" id="form1">
					{% csrf_token%}

					<input type="text" placeholder="e.g. web design" name="searchbar">
					<div style="padding-top: 5%;">
					<select name="fieldofjob"> 
						  <option value="all">Any category</option>
						  <option value="ml">Machine Learning</option>
						  <option value="appd">App Development</option>
						  <option value="webdf">Frontend Web Developmentr</option>
						  <option value="webdb">Backend Web Development</option>
						  <option value="sde">Software Development</option>
					</select>
				</div>
				</form>
				<div style="padding-top: 5%; padding-bottom: 10%;">
					<button form="form1" type="submit" class="btn btn-md btn-fill btn-info"><span
							class="glyphicon glyphicon-plus-sign"></span> Search</button>
				</div>
			</div>

		</div>
		{% if user.is_authenticated %}
		<h4>Are you a professor ?</h4>
		<div style="padding-top: 5%; padding-bottom: 10%;">
			<a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning"><span
					class="glyphicon glyphicon-plus-sign"></span> Create A BTech Project</a>
		</div>
		{% endif %}
	</div>

	{% endblock %}

	{% block group_content %}
	<div class="col-md-8" style="padding-top: 10%;">
        <h2> Available BTech Projects</h2>
		<div class="list-group">

			{% for group in object_list %}
            {% if group.btp == True %}
            {% if group.finished == False %}
			<a class="list-group-item job-list" href="{% url 'groups:single' slug=group.slug %}">
				
				<div class="salary-type col-auto order-sm-3">
					<span class="salary-range">{{ group.stipend }}</span>

					{% if group.workstatus == "pt" %}
					<span class="badge badge-success">Part-Time</span>
					{% else %}
					<span class="badge badge-success">Full-Time</span>
					{% endif %}
					<!-- <span class="badge badge-success">FullTime</span> -->
				</div>
				<div class="content col">
					<h5 class="title">{{ group.name }}</h5>
					<ul class="meta">
						<!-- <h6>{{ group.description_html|safe }}</h6> -->
						<li><strong class="text-primary"> Created by <span class="badge"> {{ group.creator.userprofile.name }}
								</span></strong>
						</li>
						<li>Number of Application{{ group.posts.count|pluralize }} <span class="badge">
								{{ group.posts.count }} </span></li>
                        <li>Branch <span class="badge">
                                {{ group.branch }} </span></li>        
					</ul>
				</div>
			</a>
            {% endif %}
            {% endif %}
			{% endfor %}
		</div>
	</div>
</div>
{% endblock %}

simplesocial/groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  {% block pregroup %}{% endblock %}
  {% block group_content %}{% endblock %}
  {% block postgroup %}{% endblock %}
</div>

{% endblock %}

simplesocial/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}

{% block group_content %}
<div style="padding-top:10%; padding-bottom: 5%;">
<h4>Create A New Intern</h4>
  <form method="POST" action="{% url 'groups:create' %}" id="groupForm">
  	{% csrf_token %}
  	{% bootstrap_form form %}
  	<input type="submit" value="Create" class="btn btn-primary btn-large">
  </form>
</div>
{% endblock %}

simplesocial/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}
{% load static %}
{% block pregroup %}
<div class="row">

	<!-- Job Sidebar Wrap End -->

	<div class="col-md-4" style="padding-top: 15%; padding-bottom: 5%;">
		<div class="content">
			{% if user.is_authenticated %}
			<h5 class="title">
				Logged in as <a href="{% url 'accounts:profile' slug=user.userprofile.username %}">@{{user.userprofile.username}}</a>
			</h5>

			{% endif %}
			<div style="padding-top: 5%; padding-bottom: 15%;">
				<h3 class="title">Search Keywords</h3>
				<form action="{% url 'groups:searchbar' %}" method="POST" id="form1">
					{% csrf_token%}

					<input type="text" placeholder="e.g. web design" name="searchbar">
					<div style="padding-top: 5%;">
					<select name="fieldofjob"> 
						  <option value="all">Any category</option>
						  <option value="ml">Machine Learning</option>
						  <option value="appd">App Development</option>
						  <option value="webdf">Frontend Web Developmentr</option>
						  <option value="webdb">Backend Web Development</option>
						  <option value="sde">Software Development</option>
					</select>
				</div>
				</form>
				<div style="padding-top: 5%; padding-bottom: 10%;">
					<button form="form1" type="submit" class="btn btn-md btn-fill btn-info"><span
							class="glyphicon glyphicon-plus-sign"></span> Search</button>
				</div>
			</div>

		</div>
		{% if user.is_authenticated %}
		<h4>Are you recruiting ?</h4>
		<div style="padding-top: 5%; padding-bottom: 10%;">
			<a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning"><span
					class="glyphicon glyphicon-plus-sign"></span> Create An Intern</a>
		</div>
		{% endif %}
	</div>

	{% endblock %}

	{% block group_content %}
	<div class="col-md-8" style="padding-top: 10%;">
		<div class="list-group">

			{% for group in object_list %}
			{% if group.finished == False %}
			<a class="list-group-item job-list" href="{% url 'groups:single' slug=group.slug %}">
				
				<div class="salary-type col-auto order-sm-3">
					<span class="salary-range">{{ group.stipend }}</span>

					{% if group.workstatus == "pt" %}
					<span class="badge badge-success">Part-Time</span>
					{% else %}
					<span class="badge badge-success">Full-Time</span>
					{% endif %}
					<!-- <span class="badge badge-success">FullTime</span> -->
				</div>
				<div class="content col">
					<h5 class="title">{{ group.name }}</h5>
					<ul class="meta">
						<!-- <h6>{{ group.description_html|safe }}</h6> -->
						<li><strong class="text-primary"> Created by <span class="badge"> {{ group.creator.userprofile.name }}
								</span></strong>
						</li>
						<li>Number of Application{{ group.posts.count|pluralize }} <span class="badge">
								{{ group.posts.count }} </span></li>
					</ul>
				</div>
			</a>
			{% endif %}
			{% endfor %}
		</div>
	</div>
</div>
{% endblock %}

simplesocial/groups/templates/groups/searchbar.html
{% extends "groups/group_base.html" %}
{% load static %}
{% block pregroup %}

<div class="row">


	<div class="col-md-4" style="padding-top: 15%; padding-bottom: 5%;">
		<div class="content">
			{% if user.is_authenticated %}
			<h5 class="title">
				Logged in as <a href="{% url 'accounts:profile' slug=user.userprofile.username %}">@{{user.userprofile.username}}</a>
			</h5>

			{% endif %}
			<div style="padding-top: 5%; padding-bottom: 15%;">
				<h3 class="title">Search Keywords</h3>
				<form action="{% url 'groups:searchbar' %}" method="POST">
					{% csrf_token%}

					<input type="text" placeholder="e.g. web design" name="searchbar">
					<div style="padding-top: 5%;">
					<select name="fieldofjob"> 
						  <option value="all">Any category</option>
						  <option value="ml">Machine Learning</option>
						  <option value="appd">App Development</option>
						  <option value="webdf">Frontend Web Developmentr</option>
						  <option value="webdb">Backend Web Development</option>
						  <option value="sde">Software Development</option>
					</select>
					</div>
				</form>
				<div style="padding-top: 5%; padding-bottom: 10%;">
					<button form="form1" type="submit" class="btn btn-md btn-fill btn-info"><span
							class="glyphicon glyphicon-plus-sign"></span> Search</button>
				</div>
			</div>

		</div>
		{% if user.is_authenticated %}
		<h4>Are you recruiting ?</h4>
		<div style="padding-top: 5%; padding-bottom: 10%;">
			<a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning"><span
					class="glyphicon glyphicon-plus-sign"></span> Create An Intern</a>
		</div>
		{% endif %}
	</div>

	{% endblock %}

	{% block group_content %}

	<div class="col-md-8" style="padding-top: 10%;">
		<div class="list-group">
			{% if groupss %}

			{% for group in groupss %}
			<a class="list-group-item job-list" href="{% url 'groups:single' slug=group.slug %}">
				
				<div class="salary-type col-auto order-sm-3">
					<span class="salary-range">{{ group.stipend }}</span>

					{% if group.workstatus == "pt" %}
					<span class="badge badge-success">Part-Time</span>
					{% else %}
					<span class="badge badge-success">Full-Time</span>
					{% endif %}
					<!-- <span class="badge badge-success">FullTime</span> -->
				</div>
				<div class="content col">
					<h5 class="title">{{ group.name }}</h5>
					<ul class="meta">
						<!-- <h6>{{ group.description_html|safe }}</h6> -->
						<li><strong class="text-primary"> Created by <span class="badge"> {{ group.creator.userprofile.name }}
								</span></strong>
						</li>
						<li>Number of Application{{ group.posts.count|pluralize }} <span class="badge">
								{{ group.posts.count }} </span></li>
					</ul>
				</div>
			</a>
			{% endfor %}
			<div style="padding-top: 3%;">
				<h6><a href="{% url 'groups:all' %} ">Click here to return back</a>
				</h6>
				{% else %}
				<h4> Sorry Could'nt Find Any Such Intern</h4>
				<h6>Try searching with a different term or click <a href="{% url 'groups:all' %} ">here</a> to return back
				</h6>
			</div>
			
			{% endif %}
		</div>
	</div>
</div>
{% endblock %}

simplesocial/groups/templates/groups/searchbar2.html
{% extends "groups/group_base.html" %}
{% load static %}
{% block pregroup %}


<!-- Job Sidebar Wrap Start -->
<!-- <div class="col-lg-4 col-12 mb-5">
	<div class="sidebar-wrap"> 
		 Sidebar (Search) Start -->
<!-- <div class="sidebar-widget">
	<div class="inner">
		<h6 class="title">Search Keywords</h6>
		<form action="https://demo.hasthemes.com/keller-preview/keller/job-list.html#">
			<input type="text" placeholder="e.g. web design">
		</form>
	</div>
</div> -->

<!-- Sidebar (Search) End -->

<!-- Sidebar (Category) Start -->
<!-- <div class="sidebar-widget">
			<div class="inner">
				<h6 class="title">Category</h6>
				<form action="https://demo.hasthemes.com/keller-preview/keller/job-list.html#">
					<select>
						<option value="1">Any category</option>
						<option value="2">Web Designer</option>
						<option value="3">Web Developer</option>
						<option value="4">Graphic Designer</option>
						<option value="5">App Developer</option>
						<option value="6">UI &amp; UX Expert</option>
					</select>
				</form>
			</div>
		</div> -->
<!-- Sidebar (Category) End -->




<!-- Sidebar (Date Posted) Start -->
<!-- <div class="sidebar-widget">
			<div class="inner">
				<h6 class="title">Date Posted</h6>
				<form action="https://demo.hasthemes.com/keller-preview/keller/job-list.html#" class="mb-n1">
					<div class="custom-control custom-radio mb-1">
						<input type="radio" class="custom-control-input" name="jobDatePosted" id="jobDatePosted0">
						<label class="custom-control-label" for="jobDatePosted0">Any Date</label>
					</div>
					<div class="custom-control custom-radio mb-1">
						<input type="radio" class="custom-control-input" name="jobDatePosted" id="jobDatePosted1">
						<label class="custom-control-label" for="jobDatePosted1">Last Hour</label>
					</div>
					<div class="custom-control custom-radio mb-1">
						<input type="radio" class="custom-control-input" name="jobDatePosted" id="jobDatePosted2">
						<label class="custom-control-label" for="jobDatePosted2">Last 24 Hours</label>
					</div>
					<div class="custom-control custom-radio mb-1">
						<input type="radio" class="custom-control-input" name="jobDatePosted" id="jobDatePosted3">
						<label class="custom-control-label" for="jobDatePosted3">Last 7 Days</label>
					</div>
					<div class="custom-control custom-radio mb-1">
						<input type="radio" class="custom-control-input" name="jobDatePosted" id="jobDatePosted4">
						<label class="custom-control-label" for="jobDatePosted4">Last 14 days</label>
					</div>
					<div class="custom-control custom-radio mb-1">
						<input type="radio" class="custom-control-input" name="jobDatePosted" id="jobDatePosted5">
						<label class="custom-control-label" for="jobDatePosted5">Last 30 days</label>
					</div>
				</form>
			</div>
		</div> -->
<!-- Sidebar (Date Posted) End -->

<!-- Sidebar (Qualification) Start -->
<!-- <div class="sidebar-widget">
			<div class="inner">
				<h6 class="title">Qualification</h6>
				<form action="https://demo.hasthemes.com/keller-preview/keller/job-list.html#" class="mb-n1">
					<div class="custom-control custom-radio mb-1">
						<input type="radio" class="custom-control-input" name="jobQualification" id="jobQualification0">
						<label class="custom-control-label" for="jobQualification0">Matriculation</label>
					</div>
					<div class="custom-control custom-radio mb-1">
						<input type="radio" class="custom-control-input" name="jobQualification" id="jobQualification1">
						<label class="custom-control-label" for="jobQualification1">Intermidiate</label>
					</div>
					<div class="custom-control custom-radio mb-1">
						<input type="radio" class="custom-control-input" name="jobQualification" id="jobQualification2">
						<label class="custom-control-label" for="jobQualification2">Gradute</label>
					</div>
				</form>
			</div>
		</div> -->
<!-- Sidebar (Qualification) End -->
<!-- </div> -->
<!-- </div> -->

<!-- Job Sidebar Wrap End -->

<div class="col-md-4" style="padding-top: 15%; padding-bottom: 5%;">
    <div class="content">
        {% if user.is_authenticated %}
        <h5 class="title">
            Logged in as <a href="{% url 'posts:for_user' username=user.username %}">@{{user.username }}</a>
        </h5>

        {% endif %}
        <div style="padding-top: 5%; padding-bottom: 15%;">
            <h3 class="title">Search Keywords</h3>
            <form action="{% url 'groups:searchbar' %}" method="POST">
                {% csrf_token%}

                <input type="text" placeholder="e.g. web design" name="searchbar">
            </form>
			<div style="padding-top: 5%; padding-bottom: 10%;">
				<button form="form1" type="submit" class="btn btn-md btn-fill btn-info"><span
						class="glyphicon glyphicon-plus-sign"></span> Search</button>
			</div>
        </div>

    </div>
    {% if user.is_authenticated %}
    <h4>Are you recruiting ?</h4>
    <div style="padding-top: 5%; padding-bottom: 10%;">
        <a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning"><span
                class="glyphicon glyphicon-plus-sign"></span> Create An Intern</a>
    </div>
    {% endif %}
</div>

{% endblock %}

{% block group_content %}
<div class="col-md-8" style="padding-top: 10%;">
    <div class="list-group">

        {% for group in groupss %}
        <a class="list-group-item job-list" href="{% url 'groups:single' slug=group.slug %}">
            <div class="company-logo col-auto">
                <img src="{% static 'Keller - Job Board HTML Template_files/company-5.png' %}" alt="Company Logo">
            </div>
            <div class="salary-type col-auto order-sm-3">
                <span class="salary-range">{{ group.income }}</span>
                <span class="badge badge-success">{{ group.workstatus }}</span>
                <!-- <span class="badge badge-success">FullTime</span> -->
            </div>
            <div class="content col">
                <h5 class="title">{{ group.name }}</h5>
                <ul class="meta">
                    <!-- <h6>{{ group.description_html|safe }}</h6> -->
                    <li><strong class="text-primary"> Created by <span class="badge"> {{ group.creator }}
                            </span></strong>
                    </li>
                    <li>Number of Application{{ group.posts.count|pluralize }} <span class="badge">
                            {{ group.posts.count }} </span></li>
                </ul>
            </div>
        </a>
        <!-- <a class="list-group-item" href="{% url 'groups:single' slug=group.slug %}">
			<h3 class="title list-group-item-heading">{{ group.name }}</h3>
			<div class="list-group-item-text container-fluid">
				{{ group.description_html|safe }}
				<div class="row">
					<div class="col-md-4">
						Created by<span class="badge"> {{ group.creator }} </span>
						Number of Application{{ group.posts.count|pluralize }} <span class="badge">{{ group.posts.count
							}}</span>
					</div>
				</div>
			</div>
		</a> -->
        {% endfor %}
    </div>
</div>
{% endblock %}

simplesocial/groups/templates/groups/yourlist.html
{% extends "groups/group_base.html" %}
{% load static %}
{% block pregroup %}
<div class="row">

	<!-- Job Sidebar Wrap End -->

	<div class="col-md-4" style="padding-top: 15%; padding-bottom: 5%;">
		<div class="content">
			{% if user.is_authenticated %}
			<h5 class="title">
				Logged in as <a href="{% url 'accounts:profile' slug=user.userprofile.username %}">@{{user.userprofile.username}}</a>
			</h5>

			{% endif %}
			<div style="padding-top: 5%; padding-bottom: 15%;">
				<h3 class="title">Search Keywords</h3>
				<form action="{% url 'groups:searchbar' %}" method="POST" id="form1">
					{% csrf_token%}

					<input type="text" placeholder="e.g. web design" name="searchbar">
					<div style="padding-top: 5%;">
					<select name="fieldofjob"> 
						  <option value="all">Any category</option>
						  <option value="ml">Machine Learning</option>
						  <option value="appd">App Development</option>
						  <option value="webdf">Frontend Web Developmentr</option>
						  <option value="webdb">Backend Web Development</option>
						  <option value="sde">Software Development</option>
					</select>
				</div>
				</form>
				<div style="padding-top: 5%; padding-bottom: 10%;">
					<button form="form1" type="submit" class="btn btn-md btn-fill btn-info"><span
							class="glyphicon glyphicon-plus-sign"></span> Search</button>
				</div>
			</div>

		</div>
		{% if user.is_authenticated %}
		<h4>Are you recruiting ?</h4>
		<div style="padding-top: 5%; padding-bottom: 10%;">
			<a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning"><span
					class="glyphicon glyphicon-plus-sign"></span> Create An Intern</a>
		</div>
		{% endif %}
	</div>

	{% endblock %}

	{% block group_content %}
	<div class="col-md-8" style="padding-top: 10%;">
		<div class="list-group">

			{% for group in object_list %}
            {% if group.creator == user %}
			<a class="list-group-item job-list" href="{% url 'groups:single' slug=group.slug %}">
				
				<div class="salary-type col-auto order-sm-3">
					<span class="salary-range">{{ group.stipend }}</span>

					{% if group.workstatus == "pt" %}
					<span class="badge badge-success">Part-Time</span>
					{% else %}
					<span class="badge badge-success">Full-Time</span>
					{% endif %}
					<!-- <span class="badge badge-success">FullTime</span> -->
				</div>
				<div class="content col">
					<h5 class="title">{{ group.name }}</h5>
					<ul class="meta">
						<!-- <h6>{{ group.description_html|safe }}</h6> -->
						<li><strong class="text-primary"> Created by <span class="badge"> {{ group.creator.userprofile.name }}
								</span></strong>
						</li>
						<li>Number of Application{{ group.posts.count|pluralize }} <span class="badge">
								{{ group.posts.count }} </span></li>
					</ul>
				</div>
			</a>
            {% endif %}
			{% endfor %}
		</div>
	</div>
</div>
{% endblock %}